name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"

jobs:
  tag:
    name: New Tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: workshopbutler/action-wordpress-plugin-deploy@develop
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: workshop-butler
        ASSETS_DIR: assets
        PLUGIN_DIR: workshop-butler
